# Generated by Django 5.0.3 on 2024-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exerciserecord_foodrecord_sleeprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeprecord',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
