# Generated by Django 5.0.3 on 2024-05-12 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_exerciserecord_activity_type_foodrecord_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.IntegerField(default=2000)),
                ('target_exercise_minutes', models.IntegerField(default=60)),
                ('target_sleep_hours', models.IntegerField(default=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
