# Generated by Django 5.0.3 on 2024-05-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_birth_date_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='活動タイプ'),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='duration',
            field=models.IntegerField(verbose_name='運動時間（分）'),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='calories',
            field=models.IntegerField(verbose_name='カロリー'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='duration',
            field=models.IntegerField(verbose_name='睡眠時間（分）'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='睡眠の質'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_calories',
            field=models.IntegerField(default=2000, verbose_name='目標カロリー'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_exercise_minutes',
            field=models.IntegerField(default=60, verbose_name='目標運動時間（分）'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_sleep_hours',
            field=models.IntegerField(default=8, verbose_name='目標睡眠時間（時間）'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
